---
- name: Create Repo Directory
  file:
    path: /srv/www/void-repo
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create Static Mirror Directories
  file:
    path: "/srv/www/void-repo/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - current
    - distfiles
    - docs
    - live
    - logos
    - man
    - static
    - void-updates
    - xlocate
  loop_control:
    label: "{{ item }}"
