---
- name: Install Packages
  xbps:
    pkg: consul
    state: present

- name: Install Core Configuration
  template:
    src: 25-base.hcl.j2
    dest: /etc/consul.d/25-base.hcl
    owner: root
    group: root
    mode: 0644
  notify:
    - consul

- name: Install retry_join Configuration
  template:
    src: 30-retry-join.hcl.j2
    dest: /etc/consul.d/30-retry-join.hcl
    owner: root
    group: root
    mode: 0644
  notify:
    - consul

- name: Install Gossip Encryption Keys
  template:
    src: 30-gossip-encryption.hcl.j2
    dest: /etc/consul.d/30-gossip-encryption.hcl
    owner: root
    group: _consul
    mode: 0640
  notify:
    - consul

- name: Enable services
  service:
    name: consul
    enabled: true
    state: started
