---
- name: Install packages
  xbps:
    pkg: nomad
    state: present

- name: Install base configuration
  template:
    src: 25-base.hcl.j2
    dest: /etc/nomad.d/25-base.hcl
    owner: root
    group: root
    mode: 0644
  notify:
    - nomad

- name: Install Consul Token
  template:
    src: 30-consul.hcl
    dest: /etc/nomad.d/30-consul.hcl
    owner: root
    group: root
    mode: 0640
  notify:
    - nomad

- name: Set Datacenter
  template:
    src: 25-dc.hcl
    dest: /etc/nomad.d/25-dc.hcl
    owner: root
    group: root
    mode: 0644
  notify:
    - nomad

- name: Install Service Config
  copy:
    src: conf
    dest: /etc/sv/nomad/conf
    owner: root
    group: root
    mode: 0644

- name: Enable services
  service:
    name: nomad
    enabled: true
    state: started

- name: Install Firewall Rules
  copy:
    src: nomad.rules
    dest: /etc/iptables.d/nomad.rules
    owner: root
    group: root
    mode: 0640
  notify:
    - iptables
