---
- hosts: hashimaster
  become: yes
  become_user: root
  become_method: sudo
  vars:
    nomad_role: server
  roles:
    - consul-server
    - vault
    - nomad-server
    - nomad-client
    - hashi-ws-fw
